const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const state={container:false,file:null};
const toast=(msg)=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000)};
function showSection(name){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$('#pageTitle').textContent={launcher:'Launcher',container:'Container',compatibility:'Compatibilidade',settings:'Configurações'}[name];if(name==='compatibility')renderDiagnostics()}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
$('#chooseBtn').addEventListener('click',()=>$('#fileInput').click());
$('#fileInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;state.file=file;$('#selectedFile').textContent=`Selecionado: ${file.name}`;$('#fileStatus').textContent='Selecionado';$('#openBtn').disabled=false;$('#activity').textContent='Arquivo local pronto para abrir.';toast('Arquivo selecionado com sucesso.');});
$('#openBtn').addEventListener('click',()=>{if(!state.file)return;const confirmOpen=$('#confirmToggle').checked;if(confirmOpen&&!confirm(`Abrir o arquivo local “${state.file.name}”?\n\nO navegador não pode executar arquivos diretamente. Ele abrirá a localização para você usar o programa de sua escolha.`))return;const url=URL.createObjectURL(state.file);const a=document.createElement('a');a.href=url;a.download=state.file.name;a.click();URL.revokeObjectURL(url);toast('Arquivo preparado. Abra-o pelo sistema operacional.');});
function createContainer(){if(state.container){showSection('launcher');toast('O container já está criado.');return}const mode=$('#displayMode').value;$('#containerStatus').textContent='Criando…';$('#modeStatus').textContent=mode;$('#progressText').textContent='Preparando container';let p=0;state.container=true;const timer=setInterval(()=>{p+=10;$('#progressBar').style.width=p+'%';$('#progressPercent').textContent=p+'%';if(p===40)$('#activity').textContent='Verificando espaço disponível…';if(p===70)$('#activity').textContent='Aplicando perfil de compatibilidade…';if(p>=100){clearInterval(timer);$('#containerStatus').textContent='Pronto';$('#progressText').textContent='Container criado';$('#activity').textContent='Container criado com segurança.';toast('Container criado com sucesso.');}},90)}
$('#createBtn').addEventListener('click',()=>{createContainer();showSection('container')});$('#createBtn2').addEventListener('click',()=>{createContainer();showSection('launcher')});
function renderDiagnostics(){const items=[['Plataforma',navigator.platform||'Indisponível'],['Navegador',navigator.userAgent.split(' ').slice(-1)[0]||'Indisponível'],['Idioma',navigator.language||'Indisponível'],['Núcleos',navigator.hardwareConcurrency?`${navigator.hardwareConcurrency} disponíveis`:'Não informado'],['Memória',navigator.deviceMemory?`~${navigator.deviceMemory} GB`:'Não informada'],['Orientação',screen.orientation?.type||'Não informada']];$('#diagnostics').innerHTML=items.map(x=>`<div class="diagnostic"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
const languageNames={'pt-BR':'Português (Brasil)','en-US':'English','es-ES':'Español','fr-FR':'Français','de-DE':'Deutsch','it-IT':'Italiano','ru-RU':'Русский','pl-PL':'Polski','ja-JP':'日本語','zh-TW':'中文','ko-KR':'한국어','es-MX':'Español (México)'};
const languageMap={pt:'pt-BR',en:'en-US',es:'es-ES',fr:'fr-FR',de:'de-DE',it:'it-IT',ru:'ru-RU',pl:'pl-PL',ja:'ja-JP',zh:'zh-TW',ko:'ko-KR'};
function normalizeLanguage(value){const key=String(value||'').replace('_','-');return languageNames[key]?key:(languageMap[key.slice(0,2)]||'en-US')}
function saveGameLanguage(code,source){localStorage.setItem('gtav.language',code);localStorage.setItem('gtav.languageSource',source);$('#gameLanguageStatus').textContent=`Idioma do GTA V: ${languageNames[code]||code} (${source})`;return code}
async function detectGameLanguage(source){
  if(source==='device') return saveGameLanguage(normalizeLanguage(navigator.language),'aparelho');
  if(source==='manual') return saveGameLanguage($('#gameLanguage').value,'manual');
  $('#gameLanguageStatus').textContent='Idioma do GTA V: consultando país do IP…';
  try{const r=await fetch('https://ipapi.co/json/');if(!r.ok)throw new Error('IP indisponível');const data=await r.json();const country=data.country_code||'';const byCountry={BR:'pt-BR',PT:'pt-BR',US:'en-US',GB:'en-US',ES:'es-ES',MX:'es-MX',FR:'fr-FR',DE:'de-DE',IT:'it-IT',RU:'ru-RU',PL:'pl-PL',JP:'ja-JP',CN:'zh-TW',TW:'zh-TW',KR:'ko-KR'};return saveGameLanguage(byCountry[country]||'en-US',`IP/${country||'desconhecido'}`)}catch(e){toast('Não foi possível consultar o IP; usando o idioma do aparelho.');return saveGameLanguage(normalizeLanguage(navigator.language),'fallback do aparelho')}
}
function initGameLanguage(){const source=localStorage.getItem('gtav.languageSource')||'device';$('#gameLanguageSource').value=source;$('#manualLanguageRow').hidden=source!=='manual';if(source==='manual')$('#gameLanguage').value=localStorage.getItem('gtav.language')||'pt-BR';detectGameLanguage(source)}
$('#gameLanguageSource').addEventListener('change',e=>{$('#manualLanguageRow').hidden=e.target.value!=='manual';detectGameLanguage(e.target.value)});$('#gameLanguage').addEventListener('change',()=>detectGameLanguage('manual'));
$('#runCheck').addEventListener('click',()=>{renderDiagnostics();toast('Verificação concluída.')});$('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('light-theme'));$('#contrastToggle').addEventListener('change',e=>document.body.classList.toggle('high-contrast',e.target.checked));$('#landscapeToggle').addEventListener('change',e=>{if(e.target.checked){$('#modeStatus').textContent='Paisagem';toast('Modo paisagem ativado.')}else{toast('Modo paisagem desativado.')}});renderDiagnostics();initGameLanguage();

// O protótipo não baixa URLs, instala APKs ou contém arquivos de terceiros.
