const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const state={container:false,file:null};
const toast=(msg)=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000)};
function showSection(name){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$('#pageTitle').textContent={launcher:'Launcher',container:'Container',compatibility:'Compatibilidade',settings:'Configurações'}[name];if(name==='compatibility')renderDiagnostics()}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
$('#chooseBtn').addEventListener('click',()=>$('#fileInput').click());
$('#fileInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;state.file=file;$('#selectedFile').textContent=`Selecionado: ${file.name}`;$('#fileStatus').textContent='Selecionado';$('#openBtn').disabled=false;$('#activity').textContent='Arquivo local pronto para abrir.';toast('Arquivo selecionado com sucesso.');});
$('#openBtn').addEventListener('click',()=>{if(!state.file)return;const confirmOpen=$('#confirmToggle').checked;if(confirmOpen&&!confirm(`Abrir o arquivo local “${state.file.name}”?\n\nO navegador não pode executar arquivos diretamente. Ele abrirá a localização para você usar o programa de sua escolha.`))return;const url=URL.createObjectURL(state.file);const a=document.createElement('a');a.href=url;a.download=state.file.name;a.click();URL.revokeObjectURL(url);toast('Arquivo preparado. Abra-o pelo sistema operacional.');});
function createContainer(){if(state.container){showSection('launcher');toast('O container já está criado.');return}const mode=$('#displayMode').value;$('#containerStatus').textContent='Criando…';$('#modeStatus').textContent=mode;$('#progressText').textContent='Preparando container';let p=0;state.container=true;const timer=setInterval(()=>{p+=10;$('#progressBar').style.width=p+'%';$('#progressPercent').textContent=p+'%';if(p===40)$('#activity').textContent='Verificando espaço disponível…';if(p===70)$('#activity').textContent='Aplicando perfil de compatibilidade…';if(p>=100){clearInterval(timer);$('#containerStatus').textContent='Pronto';$('#progressText').textContent='Container criado';$('#activity').textContent='Container criado com segurança.';toast('Container criado com sucesso.');}},90)}
$('#createBtn').addEventListener('click',()=>{createContainer();showSection('container')});$('#createBtn2').addEventListener('click',()=>{createContainer();showSection('launcher')});
function renderDiagnostics(){const items=[['Plataforma',navigator.platform||'Indisponível'],['Navegador',navigator.userAgent.split(' ').slice(-1)[0]||'Indisponível'],['Idioma',navigator.language||'Indisponível'],['Núcleos',navigator.hardwareConcurrency?`${navigator.hardwareConcurrency} disponíveis`:'Não informado'],['Memória',navigator.deviceMemory?`~${navigator.deviceMemory} GB`:'Não informada'],['Orientação',screen.orientation?.type||'Não informada']];$('#diagnostics').innerHTML=items.map(x=>`<div class="diagnostic"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
const performanceProfiles={"4GB":['480p','30 FPS','texturas baixas','efeitos desligados'],"6GB":['540p','30 FPS','texturas baixas','efeitos baixos'],"8GB":['720p','30 FPS','texturas médias','efeitos baixos'],"12GB":['720p','40 FPS','texturas médias','efeitos médios'],"16GB":['900p','60 FPS','texturas altas','efeitos médios'],"24GB":['1080p','60 FPS','texturas altas','efeitos altos']};
function initPerformanceProfile(){const panel=$('#settingsView .section-card');if(!panel||$('#deviceProfile'))return;const row=document.createElement('div');row.className='setting-row';row.innerHTML='<div><b>Perfil de desempenho</b><small>Escolha RAM e fabricante para sugerir um preset conservador.</small></div><label><select id="deviceProfile"><option value="4GB">4 GB — econômico</option><option value="6GB">6 GB — básico</option><option value="8GB" selected>8 GB — equilibrado</option><option value="12GB">12 GB — alto</option><option value="16GB">16 GB — avançado</option><option value="24GB">24 GB — máximo</option></select></label>';panel.insertBefore(row,panel.firstElementChild.nextElementSibling);const brand=document.createElement('div');brand.className='setting-row';brand.innerHTML='<div><b>Fabricante</b><small>Usado apenas para sugestão; não altera o hardware.</small></div><label><select id="deviceBrand"><option>Xiaomi/POCO</option><option>RedMagic</option><option>Samsung</option><option>Huawei</option><option>Outro</option></select></label>';panel.insertBefore(brand,row.nextElementSibling);const status=document.createElement('p');status.className='selected-file';status.id='deviceProfileStatus';panel.insertBefore(status,brand.nextElementSibling);const update=()=>{const p=performanceProfiles[$('#deviceProfile').value];status.textContent=`Preset ${$('#deviceProfile').value} / ${$('#deviceBrand').value}: ${p.join(' • ')}`;localStorage.setItem('deviceProfile',$('#deviceProfile').value);localStorage.setItem('deviceBrand',$('#deviceBrand').value)};$('#deviceProfile').value=localStorage.getItem('deviceProfile')||'8GB';$('#deviceBrand').value=localStorage.getItem('deviceBrand')||'Xiaomi/POCO';$('#deviceProfile').addEventListener('change',update);$('#deviceBrand').addEventListener('change',update);update()}
function initYouTubeLink(){const panel=$('#settingsView .section-card');if(!panel||$('#youtubeChannelLink'))return;const row=document.createElement('div');row.className='setting-row';row.innerHTML='<div><b>Canal do desenvolvedor</b><small>Canal oficial informado pelo proprietário do launcher.</small></div><a class="secondary" id="youtubeChannelLink" href="https://youtube.com/@arthur2345-thydf" target="_blank" rel="noopener noreferrer">Abrir YouTube</a>';panel.appendChild(row)}
function initRuntimeVariants(){const panel=$('#settingsView .section-card');if(!panel||$('#runtimeVariant'))return;const row=document.createElement('div');row.className='setting-row';row.innerHTML='<div><b>Runtime Winlator</b><small>Selecione Cmod, Ludashi ou Vanilla. O launcher não baixa nem incorpora APKs automaticamente.</small></div><label><select id="runtimeVariant"><option value="cmod">Cmod/Bionic</option><option value="ludashi">Ludashi</option><option value="vanilla">Vanilla</option></select></label>';panel.appendChild(row);const links=document.createElement('div');links.className='setting-row';links.innerHTML='<div><b>Fontes públicas</b><small>Os três runtimes são projetos separados; use apenas builds autorizadas.</small></div><span><a class="secondary" href="https://github.com/coffincolors/winlator" target="_blank" rel="noopener noreferrer">Cmod</a> <a class="secondary" href="https://github.com/StevenMXZ/Winlator-Ludashi" target="_blank" rel="noopener noreferrer">Ludashi</a> <a class="secondary" href="https://github.com/brunodev85/winlator" target="_blank" rel="noopener noreferrer">Vanilla</a></span>';panel.appendChild(links);const saved=localStorage.getItem('runtimeVariant');if(saved&&['cmod','ludashi','vanilla'].includes(saved))$('#runtimeVariant').value=saved;$('#runtimeVariant').addEventListener('change',e=>{localStorage.setItem('runtimeVariant',e.target.value);toast(`Runtime selecionado: ${e.target.options[e.target.selectedIndex].text}`)})}
const languageNames={'pt-BR':'Português (Brasil)','en-US':'English','es-ES':'Español','fr-FR':'Français','de-DE':'Deutsch','it-IT':'Italiano','ru-RU':'Русский','pl-PL':'Polski','ja-JP':'日本語','zh-TW':'中文','ko-KR':'한국어','es-MX':'Español (México)'};
const languageMap={pt:'pt-BR',en:'en-US',es:'es-ES',fr:'fr-FR',de:'de-DE',it:'it-IT',ru:'ru-RU',pl:'pl-PL',ja:'ja-JP',zh:'zh-TW',ko:'ko-KR'};
function normalizeLanguage(value){const key=String(value||'').replace('_','-');return languageNames[key]?key:(languageMap[key.slice(0,2)]||'en-US')}
function saveGameLanguage(code,source){localStorage.setItem('gtav.language',code);localStorage.setItem('gtav.languageSource',source);$('#gameLanguageStatus').textContent=`Idioma do GTA V: ${languageNames[code]||code} (${source})`;return code}
async function detectGameLanguage(source){
  if(source==='device') return saveGameLanguage(normalizeLanguage(navigator.language),'aparelho');
  if(source==='manual') return saveGameLanguage($('#gameLanguage').value,'manual');
  $('#gameLanguageStatus').textContent='Idioma do GTA V: consultando país do IP…';
  try{const r=await fetch('https://ipapi.co/json/');if(!r.ok)throw new Error('IP indisponível');const data=await r.json();const country=data.country_code||'';const byCountry={BR:'pt-BR',PT:'pt-BR',US:'en-US',GB:'en-US',ES:'es-ES',MX:'es-MX',FR:'fr-FR',DE:'de-DE',IT:'it-IT',RU:'ru-RU',PL:'pl-PL',JP:'ja-JP',CN:'zh-TW',TW:'zh-TW',KR:'ko-KR'};return saveGameLanguage(byCountry[country]||'en-US',`IP/${country||'desconhecido'}`)}catch(e){toast('Não foi possível consultar o IP; usando o idioma do aparelho.');return saveGameLanguage(normalizeLanguage(navigator.language),'fallback do aparelho')}
}
function initGameLanguage(){const source=localStorage.getItem('gtav.languageSource')||'device';$('#gameLanguageSource').value=source;$('#manualLanguageRow').hidden=source!=='manual';if(source==='manual')$('#gameLanguage').value=localStorage.getItem('gtav.language')||'pt-BR';detectGameLanguage(source)}
$('#gameLanguageSource').addEventListener('change',e=>{$('#manualLanguageRow').hidden=e.target.value!=='manual';detectGameLanguage(e.target.value)});$('#gameLanguage').addEventListener('change',()=>detectGameLanguage('manual'));
$('#runCheck').addEventListener('click',()=>{renderDiagnostics();toast('Verificação concluída.')});$('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('light-theme'));$('#contrastToggle').addEventListener('change',e=>document.body.classList.toggle('high-contrast',e.target.checked));$('#landscapeToggle').addEventListener('change',e=>{if(e.target.checked){$('#modeStatus').textContent='Paisagem';toast('Modo paisagem ativado.')}else{toast('Modo paisagem desativado.')}});initPerformanceProfile();initYouTubeLink();initRuntimeVariants();renderDiagnostics();initGameLanguage();

// O protótipo não baixa URLs, instala APKs ou contém arquivos de terceiros.
